// Runs automatically on every Cloudflare Pages build (see package.json "build" script).
// Reads SUPABASE_URL / SUPABASE_ANON_KEY from Cloudflare Pages env vars (Settings >
// Environment variables — plain vars, NOT secrets, since the anon key is safe client-side)
// and writes the real values into js/supabase-config.js so it's never hand-edited or
// committed with real credentials.

const fs = require('fs')
const path = require('path')

const SUPABASE_URL = process.env.SUPABASE_URL || 'https://your-project-id.supabase.co'
const SUPABASE_ANON_KEY = process.env.SUPABASE_ANON_KEY || 'your-anon-key-here'

const content = `// ── AUTO-GENERATED by build.js during the Cloudflare Pages build — do not edit by hand ──
const SUPABASE_URL = '${SUPABASE_URL}'
const SUPABASE_ANON_KEY = '${SUPABASE_ANON_KEY}'

const supabaseClient = supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true
  }
})
`

const outPath = path.join(__dirname, 'js', 'supabase-config.js')
fs.writeFileSync(outPath, content)
console.log(`Wrote ${outPath}`)

if (SUPABASE_URL.includes('your-project-id') || SUPABASE_ANON_KEY.includes('your-anon-key')) {
  console.warn(
    '\n⚠ WARNING: SUPABASE_URL / SUPABASE_ANON_KEY are not set.\n' +
    '  Login/signup/profile pages will not work until you set them in\n' +
    '  Cloudflare Pages > Settings > Environment variables (for BOTH Production and Preview).\n'
  )
}
